In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)


[[1 2 3]
 [4 5 6]]


In [4]:
print(arr.shape)      # (5,) means 1D array of length 5
print(matrix.shape)   # (2, 3) means 2 rows, 3 columns

print(arr.dtype)      # data type, e.g. int64 or float64
print(matrix.size)    # total number of elements, e.g. 6
print(matrix.ndim)       # number of dimensions, e.g. 1 or 2
print(arr.ndim)  

(5,)
(2, 3)
int64
6
2
1


In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5 7 9]
print(a * b)   # [4 10 18]
print(a - b)   # [-3 -3 -3]
print(a / b)   # [0.25 0.4 0.5]


[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [6]:
print(np.sqrt(a))       # square root: [1. 1.414 1.732]
print(np.exp(a))        # e^x
print(np.log(a))        # natural log
print(np.sin(a))        # sine values


[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]


In [7]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])       # 10
print(arr[1:4])     # [20 30 40]
print(arr[-1])      # 50 (last element)

# 2D array slicing
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix[0, 1])     # 2 (row 0, col 1)
print(matrix[:, 2])     # all rows, column 2 -> [3 6]


10
[20 30 40]
50
2
[3 6]


In [8]:
arr = np.arange(12)   # creates array 0 to 11
print(arr)

new_arr = arr.reshape(3, 4)  # 3 rows, 4 cols
print(new_arr)

zr=np.zeros((4,6))
print(zr)

zr=np.ones(4)
print(zr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1.]


In [9]:
arr, step = np.linspace(0, 1, 5, retstep=True)
print(arr)
print("Step size:", step)


[0.   0.25 0.5  0.75 1.  ]
Step size: 0.25


In [10]:
import numpy as np

# 1. Create an array of numbers from 1 to 10
arr = np.arange(1, 11)
print(arr)

# 2. Reshape it into 2 rows and 5 columns
reshaped = arr.reshape(2, 5)
print(reshaped)

# 3. Multiply every element by 3
multiplied = reshaped * 3
print(multiplied)

# 4. Print the mean of all elements
print("Mean:", multiplied.mean())


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 3  6  9 12 15]
 [18 21 24 27 30]]
Mean: 16.5


**random number**

In [11]:
import numpy as np

a = np.random.rand(5)
print(a)  # Example: [0.62 0.19 0.47 0.88 0.03]

b = np.random.randint(10, 100, size=5)
print(b)  # Example: [23 45 78 66 90]

c = np.random.randn(4)
print(c)  # Example: [-0.54  0.12 -1.02  1.88]

names = ['Raj', 'Sara', 'Maya', 'John']
picked = np.random.choice(names, size=2)
print(picked)


arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)


np.random.seed(42)
print(np.random.rand(3))  # Same output every time you run this


[0.21390577 0.56088071 0.74149608 0.47426959 0.7483761 ]
[63 94 12 85 65]
[-0.36219492  0.36358417  1.99055812 -1.07511272]
['Maya' 'Raj']
[4 3 1 2 5]
[0.37454012 0.95071431 0.73199394]


In [12]:
import numpy as np

# 1. Create arrays
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
print("Array a:", a)
print("Array b:\n", b)

# 2. Check shape and dimension
print("Shape of b:", b.shape)
print("Dimension of b:", b.ndim)

# 3. Reshape
c = np.arange(1, 10)         # [1 2 3 4 5 6 7 8 9]
print("Reshaped (3x3):\n", c.reshape(3, 3))

# 4. Zeros, Ones, Full
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((2, 3)))
print("Full:\n", np.full((2, 2), 7))

# 5. Identity matrix
print("Identity:\n", np.eye(3))

# 6. Arange and Linspace
print("Arange:", np.arange(0, 10, 2))        # [0 2 4 6 8]
print("Linspace:", np.linspace(1, 5, 4))     # [1. 2.33 3.66 5.]

# 7. Basic operations
x = np.array([10, 20, 30])
y = np.array([1, 2, 3])
print("Addition:", x + y)
print("Multiplication:", x * y)

# 8. Aggregate functions
data = np.array([4, 7, 1, 9, 2])
print("Max:", np.max(data))
print("Min:", np.min(data))
print("Mean:", np.mean(data))
print("Sum:", np.sum(data))

# 9. Axis-wise operations
mat = np.array([[1, 2, 3], [4, 5, 6]])
print("Column sum:", np.sum(mat, axis=0))  # Sum by column
print("Row sum:", np.sum(mat, axis=1))     # Sum by row

# 10. Transpose
print("Transpose:\n", mat.T)

# 11. Flatten
print("Flattened:", mat.flatten())

# 12. Concatenate arrays
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print("Concatenate:", np.concatenate([arr1, arr2]))

# 13. Unique values
print("Unique values:", np.unique([1, 2, 2, 3, 4, 4, 4]))

# 14. Sorting
print("Sorted:", np.sort([4, 1, 3, 2]))

b.argmin()
b.argmax()

Array a: [1 2 3]
Array b:
 [[1 2]
 [3 4]]
Shape of b: (2, 2)
Dimension of b: 2
Reshaped (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full:
 [[7 7]
 [7 7]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange: [0 2 4 6 8]
Linspace: [1.         2.33333333 3.66666667 5.        ]
Addition: [11 22 33]
Multiplication: [10 40 90]
Max: 9
Min: 1
Mean: 4.6
Sum: 23
Column sum: [5 7 9]
Row sum: [ 6 15]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]
Flattened: [1 2 3 4 5 6]
Concatenate: [1 2 3 4]
Unique values: [1 2 3 4]
Sorted: [1 2 3 4]


3

In [13]:
a1=np.arange(1,31).reshape(6,5)
print(a1)

print(a1[0])

print(a1[:,1])

a1[0:2,1:3]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[1 2 3 4 5]
[ 2  7 12 17 22 27]


array([[2, 3],
       [7, 8]])

In [14]:
import numpy as np

arr = np.array([2, 5, 7, 10, 1, 6])
print("Original array:", arr)

# Condition
condition = arr > 5
print("Condition mask:", condition)

# Filter
filtered = arr[arr > 5]
print("Filtered result:", filtered)


Original array: [ 2  5  7 10  1  6]
Condition mask: [False False  True  True False  True]
Filtered result: [ 7 10  6]


In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack vertically (rows)
v_stack = np.vstack((a, b))
print("Vertical Stack:\n", v_stack)

# Stack horizontally (columns)
h_stack = np.hstack((a, b))
print("Horizontal Stack:\n", h_stack)


Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]


**broadcasting**

In [16]:
c = np.array([4, 5, 6])

c+10

array([14, 15, 16])

In [17]:
c = np.array([4, 5, 6])

#shallow copy
a=c
print(a)

a[0]=1

print(a)

#deep copy

b=c.copy()

b[0]=10
print(b)

print(c)

[4 5 6]
[1 5 6]
[10  5  6]
[1 5 6]


**mulptication**

In [18]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print(a@b)

x=np.array([1,2,3,4])
y=np.array([5,6,7,8])

np.column_stack((x,y))

#split the stack

#vsplit and hsplit 

[[19 22]
 [43 50]]


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])